deployment:
  imageURL: 537124943253.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend  #ADD AWS ECR IMAGE URI
  imageVersion: IMAGE_VERSION   #dynamucally replace with SED editor
  replicas: 2
hpa:
  cpuUtilization: 12  #usually > 75

configMap:
  DB_HOST: <RDS_ENDPOINT-URL> #replace with RDS endpoint url, as we are using MySQL, already craeted in AWS.
